### ISSUE TITLE
Design a logo for the Data Literacy Playground

### ISSUE THREAD

**Issue by quirksahern** [quirksahern/DataLiteracyPlayground#1]
Should reflect sense of wonder. Think Alice, D&D cartoon and Narnia. Should appeal to 16-24yr olds.

**Comment by stephymiehle** [comment]
Hi there! 👋

Before submitting a PR or anything so formal, I thought I'd get your feelings on the direction here. I've included a multicolor version, simple black/white version, and alternate palette with a 2-color version to show the ways in which your logo might look.

![image](https://i.imgur.com/85pYeSD.png)

If you like this direction, I'd be very happy to continue on and theme your CSS, contributor badges, etc., or of course make any edits.

**Comment by stephymiehle** [comment]
Also, here is a preview of my logo design in context on a redesigned poster. Since the logotype uses a commercial font and any designs should be easy for others to edit/style, the poster below uses open-source Google Fonts (Playfair Display and Libre Franklin) that will also be available for free on the web.

![data-lit-poster](https://user-images.githubusercontent.com/6765732/47026498-211e9580-d1ad-11e8-859e-cc434527b7f9.png)

**Comment by quirksahern** [comment]
Hi,

Looks great!

Thanks. When you’re ready just make a pull request.

Am currently on holiday in the Pyrenees, will be able to respond better next week.

Sam

Sent from my iPhone

On 16 Oct 2018, at 17:08, Stephy <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, here is a preview of my logo design in context on a redesigned poster. Since the logotype uses a commercial font and any designs should be easy for others to edit/style, the poster below uses open-source Google Fonts (Playfair Display and Libre Franklin) that will also be available for free on the web.

[data-lit-poster]<https://user-images.githubusercontent.com/6765732/47026498-211e9580-d1ad-11e8-859e-cc434527b7f9.png>

**Comment by quirksahern** [comment]
Again, thank you! Looks great.
